/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:35:41 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.CheckIfLastCharIsALetter;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class CheckIfLastCharIsALetter_ESTest extends CheckIfLastCharIsALetter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        CheckIfLastCharIsALetter.checkIfLastCharIsALetter((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.CheckIfLastCharIsALetter", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Boolean boolean0 = CheckIfLastCharIsALetter.checkIfLastCharIsALetter(":12E*#cj");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Boolean boolean0 = CheckIfLastCharIsALetter.checkIfLastCharIsALetter("UxZ,Q2)|W");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Boolean boolean0 = CheckIfLastCharIsALetter.checkIfLastCharIsALetter("d");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Boolean boolean0 = CheckIfLastCharIsALetter.checkIfLastCharIsALetter("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Boolean boolean0 = CheckIfLastCharIsALetter.checkIfLastCharIsALetter("o.&Z ");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CheckIfLastCharIsALetter checkIfLastCharIsALetter0 = new CheckIfLastCharIsALetter();
  }
}
