/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:52:30 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.GenerateIntegers;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class GenerateIntegers_ESTest extends GenerateIntegers_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      List<Object> list0 = GenerateIntegers.generateIntegers(920, 2);
      assertTrue(list0.contains(2));
      assertEquals(4, list0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      List<Object> list0 = GenerateIntegers.generateIntegers(0, 0);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GenerateIntegers generateIntegers0 = new GenerateIntegers();
  }
}
