/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 22:09:32 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.GreatestCommonDivisor;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class GreatestCommonDivisor_ESTest extends GreatestCommonDivisor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = GreatestCommonDivisor.greatestCommonDivisor((-1937), (-1));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = GreatestCommonDivisor.greatestCommonDivisor(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = GreatestCommonDivisor.greatestCommonDivisor(337, 337);
      assertEquals(337, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GreatestCommonDivisor greatestCommonDivisor0 = new GreatestCommonDivisor();
  }
}
