/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:38:50 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.HowManyTimes;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class HowManyTimes_ESTest extends HowManyTimes_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = HowManyTimes.howManyTimes("original.HowManyTimes", "i");
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        HowManyTimes.howManyTimes((String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.HowManyTimes", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = HowManyTimes.howManyTimes("(IM>LqcpeyBsA?m", "");
      assertEquals(15, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = HowManyTimes.howManyTimes("H`4U?dB({V72<MN", "]\"[yR");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      HowManyTimes howManyTimes0 = new HowManyTimes();
  }
}
