/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:43:19 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.StrangeSortList;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class StrangeSortList_ESTest extends StrangeSortList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      List<Object> list0 = StrangeSortList.strangeSortList(linkedList0);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        StrangeSortList.strangeSortList((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.StrangeSortList", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Object object0 = new Object();
      Integer integer0 = new Integer((-1484));
      List<Object> list0 = List.of(object0, (Object) integer0, (Object) integer0, (Object) integer0, (Object) integer0, (Object) integer0, (Object) integer0, (Object) integer0, object0);
      List<Object> list1 = StrangeSortList.strangeSortList(list0);
      assertEquals(7, list1.size());
      assertFalse(list1.contains(object0));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      StrangeSortList strangeSortList0 = new StrangeSortList();
  }
}
