/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:10:06 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.XOrY;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class XOrY_ESTest extends XOrY_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = XOrY.xOrY(2425, 0, 19);
      assertEquals(19, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = XOrY.xOrY((-861), 0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      XOrY.xOrY(6257, (-650), 6257);
      // Undeclared exception!
      XOrY.xOrY(6257, 6257, 6257);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = XOrY.xOrY(1, 983, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      XOrY xOrY0 = new XOrY();
  }
}
