/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:25:38 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.GetOddCollatz;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GetOddCollatz_ESTest extends GetOddCollatz_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      GetOddCollatz.getOddCollatz((-3737));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      List<Integer> list0 = GetOddCollatz.getOddCollatz(3);
      assertTrue(list0.contains(3));
      assertEquals(3, list0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GetOddCollatz getOddCollatz0 = new GetOddCollatz();
  }
}
