/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:33:25 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.MakeAPile;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MakeAPile_ESTest extends MakeAPile_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      List<Integer> list0 = MakeAPile.makeAPile(0);
      assertFalse(list0.contains(0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MakeAPile.makeAPile(2213);
      MakeAPile.makeAPile(1269);
      MakeAPile.makeAPile(2213);
      MakeAPile.makeAPile(2213);
      // Undeclared exception!
      MakeAPile.makeAPile(2213);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      List<Integer> list0 = MakeAPile.makeAPile(2940);
      assertTrue(list0.contains(2940));
      assertEquals(2940, list0.size());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MakeAPile makeAPile0 = new MakeAPile();
  }
}
