/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 22:07:57 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.AllPrefixes;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AllPrefixes_ESTest extends AllPrefixes_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        AllPrefixes.allPrefixes((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.AllPrefixes", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      List<Object> list0 = AllPrefixes.allPrefixes("xHqr)smslo-<;R^");
      assertTrue(list0.contains("xHqr)smslo-<;R^"));
      assertEquals(15, list0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      List<Object> list0 = AllPrefixes.allPrefixes("");
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AllPrefixes allPrefixes0 = new AllPrefixes();
  }
}
