#!/usr/bin/env python3
"""
Create mutant datasets from Pitest-generated bytecode mutants.

Workflow per dataset (HumanEvalJava, Leetcode):
1. Run `mvn compile` to compile the project
2. Run Pitest with +EXPORT to generate mutant .class files
3. Decompile each selected mutant .class with CFR
4. Organize into mut_0, mut_1, mut_2 subdirectories

Each mut_X dataset picks one random mutant per class (different across X).
"""

import os
import pickle
import random
import re
import shutil
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
TOOLS_DIR = SCRIPT_DIR / "tools"
CFR_JAR = TOOLS_DIR / "cfr-0.152.jar"
EXPERIMENTS_DIR = SCRIPT_DIR / "data" / "experiments"

NUM_MUTANT_SETS = 3
RANDOM_SEED = 42


def run(cmd, cwd=None, check=True, timeout=600):
    result = subprocess.run(
        cmd, shell=True, cwd=cwd,
        capture_output=True, text=True, timeout=timeout
    )
    if check and result.returncode != 0:
        print(f"FAILED: {cmd}")
        print(result.stdout[-2000:] if len(result.stdout) > 2000 else result.stdout)
        print(result.stderr[-2000:] if len(result.stderr) > 2000 else result.stderr)
        sys.exit(1)
    return result


def create_dummy_test(notest_dir, package_name):
    test_dir = notest_dir / "src" / "test" / "java" / package_name
    test_dir.mkdir(parents=True, exist_ok=True)
    test_file = test_dir / "DummyTest.java"
    test_file.write_text(f"""package {package_name};
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;
public class DummyTest {{
    @Test
    public void dummy() {{
        assertTrue(true);
    }}
}}
""")
    return test_file


def remove_dummy_test(notest_dir, package_name):
    test_dir = notest_dir / "src" / "test" / "java" / package_name
    dummy = test_dir / "DummyTest.java"
    if dummy.exists():
        dummy.unlink()
    if test_dir.exists() and not any(test_dir.iterdir()):
        test_dir.rmdir()


def run_pitest(notest_dir, package_name):
    print(f"  Compiling project...")
    run("mvn compile -q", cwd=notest_dir)

    print(f"  Creating dummy test for Pitest...")
    create_dummy_test(notest_dir, package_name)

    print(f"  Running Pitest with +EXPORT...")
    run(
        f'mvn org.pitest:pitest-maven:mutationCoverage '
        f'-DtargetClasses="{package_name}.*" '
        f'-DfailWhenNoMutations=false '
        f'-Dfeatures="+EXPORT"',
        cwd=notest_dir
    )

    remove_dummy_test(notest_dir, package_name)

    export_dir = notest_dir / "target" / "pit-reports" / "export" / package_name
    if not export_dir.exists():
        print(f"  ERROR: No export directory found at {export_dir}")
        sys.exit(1)

    return export_dir


def decompile_class(class_file, extra_classpath=None):
    cmd = f'java -jar {CFR_JAR} {class_file}'
    if extra_classpath:
        cmd += f' --extraclasspath {extra_classpath}'
    result = run(cmd, check=False)
    if result.returncode != 0:
        return None
    source = result.stdout
    if "Unavailable Anonymous Inner Class" in source:
        return None
    return source


def load_class_id_mapping(notest_dir):
    pkl_path = notest_dir / "class_id_mapping.pkl"
    if pkl_path.exists():
        with open(pkl_path, "rb") as f:
            return pickle.load(f)
    return {}


def build_class_to_file_map(class_id_map, source_dir):
    """Build bidirectional mapping: class_name -> source_file_path"""
    class_to_file = {}

    for class_name, file_id in class_id_map.items():
        src = source_dir / f"{file_id}.java"
        if src.exists():
            class_to_file[class_name] = src

    return class_to_file


def build_file_to_class_map(class_to_file):
    """Reverse mapping: source_file -> class_name"""
    file_to_class = {}
    for class_name, src_path in class_to_file.items():
        file_to_class[src_path.name] = class_name
    return file_to_class


def create_mutant_datasets(dataset_name, package_name):
    print(f"\n{'='*60}")
    print(f"Creating mutants for: {dataset_name}")
    print(f"{'='*60}")

    notest_dir = EXPERIMENTS_DIR / dataset_name / "notest"
    if not notest_dir.exists():
        print(f"  ERROR: {notest_dir} does not exist")
        return

    pom_content = (notest_dir / "pom.xml").read_text()
    if "pitest" not in pom_content:
        print("  ERROR: pom.xml does not have pitest plugin configured")
        return

    export_dir = run_pitest(notest_dir, package_name)
    compiled_classes_dir = notest_dir / "target" / "classes"

    class_id_map = load_class_id_mapping(notest_dir)
    source_dir = notest_dir / "src" / "main" / "java" / package_name

    class_to_file = build_class_to_file_map(class_id_map, source_dir)
    file_to_class = build_file_to_class_map(class_to_file)

    class_dirs = sorted([d for d in export_dir.iterdir() if d.is_dir()])
    print(f"  Found {len(class_dirs)} mutated class directories")

    class_mutants = {}
    for class_dir in class_dirs:
        class_name = class_dir.name
        if "$" in class_name:
            continue

        if class_name not in class_to_file:
            continue

        mutants_dir = class_dir / "mutants"
        if not mutants_dir.exists():
            continue

        mutant_indices = sorted([
            int(d.name) for d in mutants_dir.iterdir()
            if d.is_dir() and d.name.isdigit()
        ])

        if not mutant_indices:
            continue

        class_mutants[class_name] = {
            "mutants_dir": mutants_dir,
            "indices": mutant_indices,
            "class_file_name": f"{package_name}.{class_name}.class",
            "source_file": class_to_file[class_name].name,
        }

    print(f"  {len(class_mutants)} classes have usable mutants (mapped via class_id_mapping)")

    for mut_idx in range(NUM_MUTANT_SETS):
        mut_name = f"{dataset_name}_mut_{mut_idx}"
        mut_dir = EXPERIMENTS_DIR / mut_name
        mut_notest = mut_dir / "notest"

        print(f"\n  Creating {mut_name}...")

        if mut_dir.exists():
            shutil.rmtree(mut_dir)

        mut_notest.mkdir(parents=True, exist_ok=True)
        shutil.copy2(notest_dir / "pom.xml", mut_notest / "pom.xml")
        if (notest_dir / "class_id_mapping.pkl").exists():
            shutil.copy2(
                notest_dir / "class_id_mapping.pkl",
                mut_notest / "class_id_mapping.pkl"
            )

        mut_source_dir = mut_notest / "src" / "main" / "java" / package_name
        mut_source_dir.mkdir(parents=True, exist_ok=True)

        mutated_count = 0
        copied_count = 0
        failed_decompile = []

        for source_file in sorted(source_dir.glob("*.java")):
            fname = source_file.name
            class_name = file_to_class.get(fname)

            if class_name and class_name in class_mutants:
                info = class_mutants[class_name]
                indices = info["indices"]

                rng_for_class = random.Random(RANDOM_SEED + hash(class_name))
                shuffled = indices.copy()
                rng_for_class.shuffle(shuffled)
                selected_idx = shuffled[mut_idx % len(shuffled)]

                class_file = info["mutants_dir"] / str(selected_idx) / info["class_file_name"]
                if not class_file.exists():
                    shutil.copy2(source_file, mut_source_dir / fname)
                    copied_count += 1
                    continue

                decompiled = decompile_class(class_file, extra_classpath=compiled_classes_dir)
                if decompiled is None:
                    shutil.copy2(source_file, mut_source_dir / fname)
                    copied_count += 1
                    failed_decompile.append(fname)
                    continue

                output_java = mut_source_dir / fname
                output_java.write_text(decompiled)
                mutated_count += 1
            else:
                shutil.copy2(source_file, mut_source_dir / fname)
                copied_count += 1

        print(f"    Mutated: {mutated_count}, Copied unchanged: {copied_count}")
        if failed_decompile:
            print(f"    Failed to decompile: {failed_decompile}")

        print(f"    Verifying compilation...")
        ansi_escape = re.compile(r'\x1b\[[0-9;]*m')
        max_fix_rounds = 5
        for fix_round in range(max_fix_rounds):
            result = run("mvn compile 2>&1", cwd=mut_notest, check=False)
            if result.returncode == 0:
                print(f"    Compilation OK!")
                break
            output = result.stdout + result.stderr
            clean_output = ansi_escape.sub('', output)
            error_files = set()
            for line in clean_output.split("\n"):
                if "ERROR" in line and ".java:" in line:
                    match = re.search(r'/([^/]+\.java):', line)
                    if match:
                        error_files.add(match.group(1))

            if error_files:
                print(f"    Round {fix_round+1}: reverting {len(error_files)} files...")
                for ef in error_files:
                    original = source_dir / ef
                    target_f = mut_source_dir / ef
                    if original.exists() and target_f.exists():
                        shutil.copy2(original, target_f)
            else:
                print(f"    WARNING: Could not identify error files")
                break
        else:
            print(f"    WARNING: Still has compilation errors after {max_fix_rounds} rounds")

    print(f"\n  Cleaning up build artifacts...")
    dirs_to_clean = [notest_dir / "target"] + [
        EXPERIMENTS_DIR / f"{dataset_name}_mut_{i}" / "notest" / "target"
        for i in range(NUM_MUTANT_SETS)
    ]
    for d in dirs_to_clean:
        if d.exists():
            shutil.rmtree(d)

    dummy_test_dir = notest_dir / "src" / "test" / "java" / package_name
    dummy_test = dummy_test_dir / "DummyTest.java"
    if dummy_test.exists():
        dummy_test.unlink()
    if dummy_test_dir.exists() and not any(dummy_test_dir.iterdir()):
        dummy_test_dir.rmdir()


def verify_mutants_differ(dataset_name, package_name):
    """Verify that mutant datasets actually differ from the original."""
    print(f"\n  Verifying mutants differ from original for {dataset_name}...")
    source_dir = EXPERIMENTS_DIR / dataset_name / "notest" / "src" / "main" / "java" / package_name

    for mut_idx in range(NUM_MUTANT_SETS):
        mut_source = EXPERIMENTS_DIR / f"{dataset_name}_mut_{mut_idx}" / "notest" / "src" / "main" / "java" / package_name
        if not mut_source.exists():
            print(f"    {dataset_name}_mut_{mut_idx}: MISSING")
            continue

        diff_count = 0
        same_count = 0
        for orig_file in sorted(source_dir.glob("*.java")):
            mut_file = mut_source / orig_file.name
            if not mut_file.exists():
                continue
            if orig_file.read_text() != mut_file.read_text():
                diff_count += 1
            else:
                same_count += 1

        print(f"    {dataset_name}_mut_{mut_idx}: {diff_count} mutated, {same_count} unchanged")


if __name__ == "__main__":
    if not CFR_JAR.exists():
        print(f"ERROR: CFR not found at {CFR_JAR}")
        sys.exit(1)

    create_mutant_datasets("HumanEvalJava", "original")
    create_mutant_datasets("Leetcode", "original")

    verify_mutants_differ("HumanEvalJava", "original")
    verify_mutants_differ("Leetcode", "original")

    print("\n" + "=" * 60)
    print("Done! Created mutant datasets:")
    for ds in ["HumanEvalJava", "Leetcode"]:
        for i in range(NUM_MUTANT_SETS):
            mut_dir = EXPERIMENTS_DIR / f"{ds}_mut_{i}"
            if mut_dir.exists():
                src_dir = mut_dir / "notest" / "src" / "main" / "java" / "original"
                count = len(list(src_dir.glob("*.java"))) if src_dir.exists() else 0
                print(f"  {ds}_mut_{i}: {count} source files")
    print("=" * 60)
