/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:04:26 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Bf;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Bf_ESTest extends Bf_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      List<Object> list0 = Bf.bf("Jupiter", "Venus");
      assertEquals(2, list0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      List<Object> list0 = Bf.bf("Venus", "Venus");
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      List<Object> list0 = Bf.bf("Earth", "7={S1 ^#`Y2;n");
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      List<Object> list0 = Bf.bf("Venus", "Jupiter");
      assertFalse(list0.contains("Jupiter"));
      assertEquals(2, list0.size());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      List<Object> list0 = Bf.bf("", "Jupiter");
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Bf bf0 = new Bf();
  }
}
