/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:34:37 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.ChooseNum;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class ChooseNum_ESTest extends ChooseNum_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = ChooseNum.chooseNum(1907, 2525);
      assertEquals(2524, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ChooseNum.chooseNum((-5125), 0);
      // Undeclared exception!
      ChooseNum.chooseNum((-5125), (-1));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = ChooseNum.chooseNum(3709, (-74));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ChooseNum chooseNum0 = new ChooseNum();
  }
}
