/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:23:27 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Digitsum;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Digitsum_ESTest extends Digitsum_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = Digitsum.digitSum("A:M@l\"JJJC/'7aj=");
      assertEquals(431, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = Digitsum.digitSum("");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        Digitsum.digitSum((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Digitsum", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = Digitsum.digitSum("MVQ^}$hi4B@Z^{s|7");
      assertEquals(400, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Digitsum digitsum0 = new Digitsum();
  }
}
