/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 22:12:38 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Fib;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Fib_ESTest extends Fib_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = Fib.fib((-2108920905));
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      Fib.fib(146906594);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = Fib.fib(2506);
      assertEquals((-2108920905), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Fib fib0 = new Fib();
  }
}
