/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:36:42 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.FindClosestElements;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class FindClosestElements_ESTest extends FindClosestElements_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      Double double0 = new Double(1.0);
      Double double1 = new Double(3607.5046204737346);
      linkedList0.add(double1);
      linkedList0.add(double0);
      linkedList0.push(double1);
      List<Double> list0 = FindClosestElements.findClosestElements(linkedList0);
      assertFalse(list0.contains(1.0));
      assertTrue(list0.contains(3607.5046204737346));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      List<Double> list0 = FindClosestElements.findClosestElements(linkedList0);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      Double double0 = new Double((-1036.971375274));
      linkedList0.add(double0);
      List<Double> list0 = linkedList0.subList(1, 1);
      linkedList0.add(double0);
      // Undeclared exception!
      try { 
        FindClosestElements.findClosestElements(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractList$SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        FindClosestElements.findClosestElements((List<Double>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.FindClosestElements", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Double double0 = new Double((-556.312));
      List<Double> list0 = List.of(double0, double0, double0, double0, double0);
      List<Double> list1 = FindClosestElements.findClosestElements(list0);
      assertEquals(2, list1.size());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FindClosestElements findClosestElements0 = new FindClosestElements();
  }
}
