/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:16:05 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.HasCloseElements;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class HasCloseElements_ESTest extends HasCloseElements_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      Double double0 = new Double(0.0);
      linkedList0.add(double0);
      linkedList0.add(double0);
      Double double1 = new Double((-1311.8));
      Boolean boolean0 = HasCloseElements.hasCloseElements(linkedList0, double1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      Double double0 = new Double((-422.884952));
      List<Double> list0 = linkedList0.subList(0, 0);
      linkedList0.push(double0);
      // Undeclared exception!
      try { 
        HasCloseElements.hasCloseElements(list0, double0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractList$SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        HasCloseElements.hasCloseElements((List<Double>) null, (Double) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.HasCloseElements", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Double double0 = new Double(0.43720633310629886);
      List<Double> list0 = List.of(double0, double0, double0, double0);
      Boolean boolean0 = HasCloseElements.hasCloseElements(list0, double0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Double double0 = new Double(0.0);
      List<Double> list0 = List.of(double0, double0, double0, double0);
      Boolean boolean0 = HasCloseElements.hasCloseElements(list0, double0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      HasCloseElements hasCloseElements0 = new HasCloseElements();
  }
}
