/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 22:07:46 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Intersperse;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Intersperse_ESTest extends Intersperse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      List<Object> list0 = Intersperse.intersperse(linkedList0, 1);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        Intersperse.intersperse((List<Object>) null, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Intersperse", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Intersperse intersperse0 = new Intersperse();
      List<Object> list0 = List.of((Object) intersperse0, (Object) intersperse0, (Object) intersperse0);
      List<Object> list1 = Intersperse.intersperse(list0, (-1));
      assertEquals(5, list1.size());
      assertTrue(list1.contains((-1)));
  }
}
