/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:53:53 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.IntToMiniRoman;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class IntToMiniRoman_ESTest extends IntToMiniRoman_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = IntToMiniRoman.intToMiniRoman((-3225));
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = IntToMiniRoman.intToMiniRoman(767);
      assertEquals("dcclxvii", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IntToMiniRoman intToMiniRoman0 = new IntToMiniRoman();
  }
}
