/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:02:54 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.LargestSmallestIntegers;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class LargestSmallestIntegers_ESTest extends LargestSmallestIntegers_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer(497);
      Integer integer1 = new Integer(8);
      Object object0 = new Object();
      List<Object> list0 = List.of((Object) integer1, (Object) integer0, (Object) integer0, (Object) integer1, object0, (Object) integer0, object0, object0);
      // Undeclared exception!
      try { 
        LargestSmallestIntegers.largestSmallestIntegers(list0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class java.lang.Object cannot be cast to class java.lang.Integer (java.lang.Object and java.lang.Integer are in module java.base of loader 'bootstrap')
         //
         verifyException("original.LargestSmallestIntegers", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer integer0 = new Integer((-1999));
      Integer integer1 = new Integer((-3103));
      Object object0 = new Object();
      List<Object> list0 = List.of((Object) integer0, (Object) integer0, (Object) integer1, object0, (Object) integer0, object0, object0, (Object) integer0);
      // Undeclared exception!
      try { 
        LargestSmallestIntegers.largestSmallestIntegers(list0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class java.lang.Object cannot be cast to class java.lang.Integer (java.lang.Object and java.lang.Integer are in module java.base of loader 'bootstrap')
         //
         verifyException("original.LargestSmallestIntegers", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      List<Object> list0 = linkedList0.subList(0, 0);
      Integer integer0 = new Integer(0);
      linkedList0.offerLast(integer0);
      // Undeclared exception!
      try { 
        LargestSmallestIntegers.largestSmallestIntegers(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractList$SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        LargestSmallestIntegers.largestSmallestIntegers((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.LargestSmallestIntegers", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      List<Integer> list0 = LargestSmallestIntegers.largestSmallestIntegers(linkedList0);
      Object object0 = new Object();
      Integer integer0 = new Integer(0);
      List<Object> list1 = List.of((Object) integer0, (Object) linkedList0, (Object) integer0, (Object) list0, object0);
      // Undeclared exception!
      try { 
        LargestSmallestIntegers.largestSmallestIntegers(list1);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class java.util.LinkedList cannot be cast to class java.lang.Integer (java.util.LinkedList and java.lang.Integer are in module java.base of loader 'bootstrap')
         //
         verifyException("original.LargestSmallestIntegers", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Integer integer0 = new Integer(477);
      List<Object> list0 = List.of((Object) integer0, (Object) integer0, (Object) integer0);
      List<Integer> list1 = LargestSmallestIntegers.largestSmallestIntegers(list0);
      assertTrue(list1.contains(477));
      assertEquals(2, list1.size());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Integer integer0 = new Integer((-283));
      List<Object> list0 = List.of((Object) integer0, (Object) integer0);
      List<Integer> list1 = LargestSmallestIntegers.largestSmallestIntegers(list0);
      assertTrue(list1.contains((-283)));
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      LargestSmallestIntegers largestSmallestIntegers0 = new LargestSmallestIntegers();
  }
}
