/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:15:03 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.SortArray;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class SortArray_ESTest extends SortArray_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer((-2376));
      Integer integer1 = new Integer((-1676));
      List<Object> list0 = List.of((Object) integer0, (Object) integer1, (Object) integer1, (Object) integer1, (Object) integer0);
      List<Object> list1 = SortArray.sortArray(list0);
      assertFalse(list1.equals((Object)list0));
      assertEquals(5, list1.size());
      assertTrue(list1.contains((-2376)));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer integer0 = new Integer(1);
      Integer integer1 = new Integer(0);
      List<Object> list0 = List.of((Object) integer0, (Object) integer0, (Object) integer0, (Object) integer1);
      List<Object> list1 = SortArray.sortArray(list0);
      List<Object> list2 = SortArray.sortArray(list1);
      assertFalse(list2.equals((Object)list0));
      assertEquals(4, list2.size());
      assertNotSame(list2, list1);
      assertTrue(list1.contains(1));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        SortArray.sortArray((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.SortArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Object object0 = new Object();
      linkedList0.add(object0);
      // Undeclared exception!
      try { 
        SortArray.sortArray(linkedList0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class java.lang.Object cannot be cast to class java.lang.Number (java.lang.Object and java.lang.Number are in module java.base of loader 'bootstrap')
         //
         verifyException("original.SortArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Integer integer0 = new Integer(4081);
      Integer integer1 = new Integer(597);
      List<Object> list0 = List.of((Object) integer0, (Object) integer1);
      List<Object> list1 = SortArray.sortArray(list0);
      assertFalse(list1.equals((Object)list0));
      assertTrue(list1.contains(4081));
      assertEquals(2, list1.size());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      List<Object> list0 = List.of();
      List<Object> list1 = SortArray.sortArray(list0);
      assertTrue(list1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SortArray sortArray0 = new SortArray();
  }
}
