/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:10:18 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Specialfilter;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Specialfilter_ESTest extends Specialfilter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer((-124));
      Integer integer1 = new Integer(10);
      Object object0 = new Object();
      List<Object> list0 = List.of((Object) integer0, (Object) integer0, (Object) integer1, object0, (Object) integer1, (Object) integer0, object0, (Object) integer0, object0);
      // Undeclared exception!
      try { 
        Specialfilter.specialfilter(list0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class java.lang.Object cannot be cast to class java.lang.Integer (java.lang.Object and java.lang.Integer are in module java.base of loader 'bootstrap')
         //
         verifyException("original.Specialfilter", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        Specialfilter.specialfilter((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Specialfilter", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Integer integer0 = new Integer(1174);
      List<Object> list0 = List.of((Object) integer0);
      int int0 = Specialfilter.specialfilter(list0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Integer integer0 = new Integer(4932);
      List<Object> list0 = List.of((Object) integer0);
      int int0 = Specialfilter.specialfilter(list0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Integer integer0 = new Integer(363);
      List<Object> list0 = List.of((Object) integer0);
      int int0 = Specialfilter.specialfilter(list0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Specialfilter specialfilter0 = new Specialfilter();
  }
}
