/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 22:05:03 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.StringToMd5;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class StringToMd5_ESTest extends StringToMd5_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        StringToMd5.stringToMd5((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = StringToMd5.stringToMd5("Wbm%");
      assertNotNull(string0);
      assertEquals("02bb18fc620b848fab315ff400363c23", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = StringToMd5.stringToMd5("");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      StringToMd5 stringToMd5_0 = new StringToMd5();
  }
}
