/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:54:28 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Encrypt;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Encrypt_ESTest extends Encrypt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = Encrypt.encrypt("wzqoqvit.Evkzgxb");
      assertEquals("adusuzmx.Ezodkbf", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = Encrypt.encrypt("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        Encrypt.encrypt((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Encrypt", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = Encrypt.encrypt("{0:r5A=7pIX>-");
      assertEquals("{0:v5A=7tIX>-", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String string0 = Encrypt.encrypt("original.Encrypt");
      assertEquals("svmkmrep.Ergvctx", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Encrypt encrypt0 = new Encrypt();
  }
}
