/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:52:22 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.FilterIntegers;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FilterIntegers_ESTest extends FilterIntegers_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      linkedList0.add((Object) linkedList0);
      List<Object> list0 = linkedList0.subList(1, 1);
      linkedList0.add((Object) linkedList0);
      // Undeclared exception!
      try { 
        FilterIntegers.filterIntegers(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractList$SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        FilterIntegers.filterIntegers((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.FilterIntegers", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Integer integer0 = new Integer(1728);
      Object object0 = new Object();
      List<Object> list0 = List.of((Object) integer0, (Object) integer0, (Object) integer0, (Object) integer0, object0);
      List<Object> list1 = FilterIntegers.filterIntegers(list0);
      assertEquals(4, list1.size());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FilterIntegers filterIntegers0 = new FilterIntegers();
      List<Object> list0 = List.of((Object) filterIntegers0, (Object) filterIntegers0);
      List<Object> list1 = FilterIntegers.filterIntegers(list0);
      assertTrue(list1.isEmpty());
  }
}
