/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 19:38:14 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.VowelsCount;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class VowelsCount_ESTest extends VowelsCount_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = VowelsCount.vowelsCount("rPtAQ5,Jjw6z");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        VowelsCount.vowelsCount((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.VowelsCount", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = VowelsCount.vowelsCount("-:}t!3v^cz56,#cy");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = VowelsCount.vowelsCount("");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int int0 = VowelsCount.vowelsCount("a&29_B-4ktC{hZ&U-t");
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      int int0 = VowelsCount.vowelsCount("@YW?  wxc?l~OxqdE ");
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      int int0 = VowelsCount.vowelsCount("HlI^wsK'[");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      int int0 = VowelsCount.vowelsCount("k ]LBe?#E=+TY");
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      int int0 = VowelsCount.vowelsCount("original.VowelsCount");
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      VowelsCount vowelsCount0 = new VowelsCount();
  }
}
