/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:56:01 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.BelowZero;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BelowZero_ESTest extends BelowZero_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer((-663));
      Integer integer1 = new Integer(0);
      Object object0 = new Object();
      List<Object> list0 = List.of((Object) integer1, object0, (Object) integer1, (Object) integer0);
      // Undeclared exception!
      try { 
        BelowZero.belowZero(list0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid operation type
         //
         verifyException("original.BelowZero", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        BelowZero.belowZero((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.BelowZero", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Integer integer0 = new Integer((-663));
      linkedList0.add(integer0);
      LinkedList<Object> linkedList1 = new LinkedList<Object>(linkedList0);
      Boolean boolean0 = BelowZero.belowZero(linkedList1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Integer integer0 = new Integer(3);
      Object object0 = new Object();
      List<Object> list0 = List.of((Object) integer0, object0, (Object) integer0, (Object) integer0, (Object) integer0, (Object) integer0);
      // Undeclared exception!
      try { 
        BelowZero.belowZero(list0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid operation type
         //
         verifyException("original.BelowZero", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer(3);
      linkedList0.add((Object) integer0);
      Boolean boolean0 = BelowZero.belowZero(linkedList0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      BelowZero belowZero0 = new BelowZero();
  }
}
