/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:58:12 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.ReverseDelete;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ReverseDelete_ESTest extends ReverseDelete_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      List<Object> list0 = ReverseDelete.reverseDelete("4O$hoG'=Ux", "l;B/7w,Rbi3-$");
      assertFalse(list0.contains("l;B/7w,Rbi3-$"));
      assertEquals(2, list0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        ReverseDelete.reverseDelete((String) null, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.ReverseDelete", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      List<Object> list0 = ReverseDelete.reverseDelete("{f>gKUG{", "");
      assertFalse(list0.contains(""));
      assertEquals(2, list0.size());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      List<Object> list0 = ReverseDelete.reverseDelete(";", ";");
      assertFalse(list0.contains(";"));
      assertEquals(2, list0.size());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ReverseDelete reverseDelete0 = new ReverseDelete();
  }
}
