/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 22:18:19 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.StringSequence;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class StringSequence_ESTest extends StringSequence_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = StringSequence.stringSequence((-2521));
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StringSequence.stringSequence(5042);
      // Undeclared exception!
      StringSequence.stringSequence(5042);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StringSequence stringSequence0 = new StringSequence();
  }
}
