/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:34:17 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.TotalMatch;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TotalMatch_ESTest extends TotalMatch_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      List<Object> list0 = List.of((Object) "]mh-V7:");
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      List<Object> list1 = TotalMatch.totalMatch(linkedList0, list0);
      assertFalse(list1.contains("]mh-V7:"));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      linkedList0.add((Object) "");
      List<Object> list0 = TotalMatch.totalMatch(linkedList0, linkedList0);
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Object object0 = new Object();
      List<Object> list0 = linkedList0.subList(0, 0);
      linkedList0.add(object0);
      // Undeclared exception!
      try { 
        TotalMatch.totalMatch(list0, linkedList0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractList$SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        TotalMatch.totalMatch((List<Object>) null, (List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.TotalMatch", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      List<Object> list0 = List.of((Object) "p2%", (Object) "p2%", (Object) "p2%", (Object) "p2%");
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      List<Object> list1 = TotalMatch.totalMatch(list0, linkedList0);
      assertFalse(list1.contains("p2%"));
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      List<Object> list0 = List.of((Object) "6C", (Object) "6C", (Object) "6C", (Object) "6C");
      List<Object> list1 = TotalMatch.totalMatch(list0, list0);
      assertTrue(list1.contains("6C"));
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TotalMatch totalMatch0 = new TotalMatch();
      List<Object> list0 = List.of((Object) totalMatch0, (Object) totalMatch0);
      List<Object> list1 = TotalMatch.totalMatch(list0, list0);
      assertEquals(2, list1.size());
  }
}
