/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 19:53:30 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.FileNameCheck;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FileNameCheck_ESTest extends FileNameCheck_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = FileNameCheck.fileNameCheck("g5:.dll");
      assertEquals("Yes", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = FileNameCheck.fileNameCheck("5qK>#/..<}ICG&J$a");
      assertEquals("No", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        FileNameCheck.fileNameCheck((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.FileNameCheck", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = FileNameCheck.fileNameCheck("I214.dll");
      assertEquals("Yes", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String string0 = FileNameCheck.fileNameCheck(":.dll");
      assertEquals("No", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String string0 = FileNameCheck.fileNameCheck(".dll");
      assertEquals("No", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String string0 = FileNameCheck.fileNameCheck(".aH3G/f}!");
      assertEquals("No", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String string0 = FileNameCheck.fileNameCheck("9nStIbfVpV!");
      assertEquals("No", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      String string0 = FileNameCheck.fileNameCheck("L4214.dll");
      assertEquals("No", string0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      FileNameCheck fileNameCheck0 = new FileNameCheck();
  }
}
