/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 19:48:34 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Minpath;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Minpath_ESTest extends Minpath_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<List<Integer>> linkedList0 = new LinkedList<List<Integer>>();
      Minpath.minpath(linkedList0, 6001);
      // Undeclared exception!
      Minpath.minpath(linkedList0, 6001);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<List<Integer>> linkedList0 = new LinkedList<List<Integer>>();
      List<Integer> list0 = Minpath.minpath(linkedList0, 1572);
      linkedList0.add(list0);
      // Undeclared exception!
      try { 
        Minpath.minpath(linkedList0, 1572);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.ArrayList$Itr", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        Minpath.minpath((List<List<Integer>>) null, 1609);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Minpath", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedList<List<Integer>> linkedList0 = new LinkedList<List<Integer>>();
      List<Integer> list0 = Minpath.minpath(linkedList0, 1);
      LinkedList<Integer> linkedList1 = new LinkedList<Integer>();
      List<List<Integer>> list1 = List.of(list0, list0, list0, list0, list0, (List<Integer>) linkedList1, (List<Integer>) linkedList1);
      // Undeclared exception!
      try { 
        Minpath.minpath(list1, 1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<List<Integer>> linkedList0 = new LinkedList<List<Integer>>();
      List<Integer> list0 = List.of();
      linkedList0.add(list0);
      // Undeclared exception!
      try { 
        Minpath.minpath(linkedList0, (-4505));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      List<Integer> list0 = List.of(integer0, integer0);
      List<List<Integer>> list1 = List.of(list0);
      List<Integer> list2 = Minpath.minpath(list1, (-1));
      assertFalse(list1.contains(list2));
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LinkedList<List<Integer>> linkedList0 = new LinkedList<List<Integer>>();
      List<Integer> list0 = Minpath.minpath(linkedList0, 1636);
      List<List<Integer>> list1 = List.of(list0, list0, list0, list0, list0, list0, list0, list0, list0, list0);
      Minpath.minpath(list1, 0);
      assertFalse(list0.contains(0));
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Minpath minpath0 = new Minpath();
  }
}
