/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:13:02 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.SplitWords;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SplitWords_ESTest extends SplitWords_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Object object0 = SplitWords.splitWords("<\"JA?|j\"W/Fbz");
      assertEquals(3, object0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Object object0 = SplitWords.splitWords("Y/QQ:kU/jUaGJ0j");
      assertEquals(2, object0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        SplitWords.splitWords((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.SplitWords", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Object object0 = SplitWords.splitWords("5?JI,V");
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Object object0 = SplitWords.splitWords(" !:8\"`3}`=h");
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SplitWords splitWords0 = new SplitWords();
  }
}
