/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:16:35 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.XOrY;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class XOrY_ESTest extends XOrY_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = XOrY.xOrY(3585, (-95), 1506);
      assertEquals(1506, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = XOrY.xOrY((-1), (-1), 2);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      XOrY.xOrY(5927, 5927, 5927);
      // Undeclared exception!
      XOrY.xOrY(5927, 5927, 5927);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = XOrY.xOrY(1, 653, (-2280));
      assertEquals((-2280), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int int0 = XOrY.xOrY(1999, 0, (-1));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      XOrY xOrY0 = new XOrY();
  }
}
