/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:04:18 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Bf;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Bf_ESTest extends Bf_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      List<Object> list0 = Bf.bf("Saturn", "Saturn");
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      List<Object> list0 = Bf.bf("Neptune", "Saturn");
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      List<Object> list0 = Bf.bf("Earth", "%nT68~HTb~<-:Cg");
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      List<Object> list0 = Bf.bf("Earth", "Saturn");
      assertEquals(2, list0.size());
      assertFalse(list0.contains("Saturn"));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      List<Object> list0 = Bf.bf("5bY???XIGcNqjN5", "5bY???XIGcNqjN5");
      assertFalse(list0.contains("5bY???XIGcNqjN5"));
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Bf bf0 = new Bf();
  }
}
