/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:56:56 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.MaxElement;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MaxElement_ESTest extends MaxElement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Integer integer0 = new Integer(1109);
      linkedList0.add(integer0);
      Integer integer1 = Integer.getInteger((String) null, 946);
      linkedList0.offerLast(integer1);
      int int0 = MaxElement.maxElement(linkedList0);
      assertEquals(1109, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer[] integerArray0 = new Integer[5];
      Integer integer0 = new Integer(0);
      integerArray0[0] = integer0;
      integerArray0[1] = integer0;
      integerArray0[2] = integerArray0[1];
      integerArray0[3] = integerArray0[1];
      integerArray0[4] = integerArray0[1];
      List<Integer> list0 = List.of(integerArray0);
      int int0 = MaxElement.maxElement(list0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        MaxElement.maxElement((List<Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.MaxElement", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Integer integer0 = Integer.getInteger("NL._OlB]?r7Zw", (-3822));
      List<Integer> list0 = List.of(integer0, integer0);
      int int0 = MaxElement.maxElement(list0);
      assertEquals((-3822), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MaxElement maxElement0 = new MaxElement();
  }
}
