/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:32:50 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.StrongestExtension;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class StrongestExtension_ESTest extends StrongestExtension_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("kS=nN5");
      linkedList0.add("original.StrongestExtension");
      String string0 = StrongestExtension.strongestExtension("GMsTpMSw;?", linkedList0);
      assertEquals("GMsTpMSw;?.kS=nN5", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      String string0 = StrongestExtension.strongestExtension("KVrlhqT`>tS", linkedList0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add((String) null);
      List<String> list0 = linkedList0.subList(0, 0);
      linkedList0.removeLastOccurrence((Object) null);
      // Undeclared exception!
      try { 
        StrongestExtension.strongestExtension("", list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractList$SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        StrongestExtension.strongestExtension("4VmS!Uzrl", (List<String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.StrongestExtension", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      List<String> list0 = List.of("", "", "'Z}q_!1mL33B)");
      String string0 = StrongestExtension.strongestExtension("", list0);
      assertEquals(".'Z}q_!1mL33B)", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      StrongestExtension strongestExtension0 = new StrongestExtension();
  }
}
