/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 19:40:37 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.SelectWords;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SelectWords_ESTest extends SelectWords_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      List<Object> list0 = SelectWords.selectWords("P CO{n]jh:+G'Hd|y", 1);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        SelectWords.selectWords((String) null, 4711);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.SelectWords", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      List<Object> list0 = SelectWords.selectWords("8U+K", 15);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      List<Object> list0 = SelectWords.selectWords("]n<+m)M<IVlpFL", (-550));
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      List<Object> list0 = SelectWords.selectWords("n9&7!FEM_{})p", (-1558));
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      List<Object> list0 = SelectWords.selectWords("original.SelectWords", (-2445));
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      List<Object> list0 = SelectWords.selectWords("3bA,;RbsW9J@w*PaFu", 0);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SelectWords selectWords0 = new SelectWords();
  }
}
