/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 22:11:02 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Solve1;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Solve1_ESTest extends Solve1_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = Solve1.solve(94);
      assertEquals("1101", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = Solve1.solve((-759));
      assertEquals("0", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solve1 solve1_0 = new Solve1();
  }
}
