/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:54:08 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Multiply;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Multiply_ESTest extends Multiply_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = Multiply.multiply(356, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = Multiply.multiply(0, (-3654));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = Multiply.multiply((-674), 955);
      assertEquals(20, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Multiply multiply0 = new Multiply();
  }
}
