/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:16:22 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.XOrY;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class XOrY_ESTest extends XOrY_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      XOrY.xOrY(5179, (-2556), (-2556));
      // Undeclared exception!
      XOrY.xOrY(5179, 5179, (-2556));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = XOrY.xOrY(691, (-1391), 0);
      assertEquals((-1391), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = XOrY.xOrY((-1347), 1658, 1454);
      assertEquals(1658, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = XOrY.xOrY(1, 1, 3736);
      assertEquals(3736, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int int0 = XOrY.xOrY(1658, 1, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      XOrY xOrY0 = new XOrY();
  }
}
