/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:34:18 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.ChooseNum;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class ChooseNum_ESTest extends ChooseNum_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ChooseNum chooseNum0 = new ChooseNum();
      ChooseNum.chooseNum((-1), (-1));
      int int0 = 5308;
      ChooseNum.chooseNum((-1), 5308);
      // Undeclared exception!
      ChooseNum.chooseNum(1, 5308);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = ChooseNum.chooseNum((-490), (-490));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = ChooseNum.chooseNum(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = 284;
      ChooseNum.chooseNum(284, 0);
      ChooseNum chooseNum0 = new ChooseNum();
      int int1 = (-2560);
      ChooseNum.chooseNum(0, (-2560));
      ChooseNum.chooseNum(0, 0);
      ChooseNum.chooseNum((-2560), 2145);
      ChooseNum.chooseNum(0, 0);
      int int2 = (-213);
      ChooseNum.chooseNum(0, (-213));
      ChooseNum.chooseNum((-2560), 2145);
      ChooseNum.chooseNum(2144, (-2560));
      // Undeclared exception!
      ChooseNum.chooseNum(0, 2498);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int int0 = ChooseNum.chooseNum((-1), (-1));
      assertEquals((-1), int0);
  }
}
