/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:05:55 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Common;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Common_ESTest extends Common_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      List<Integer> list0 = linkedList0.subList(0, 0);
      Integer integer0 = new Integer(1);
      linkedList0.add(integer0);
      LinkedList<Object> linkedList1 = new LinkedList<Object>();
      // Undeclared exception!
      try { 
        Common.common(list0, linkedList1);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractList$SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      // Undeclared exception!
      try { 
        Common.common(linkedList0, (List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Common", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Integer integer1 = new Integer(3831);
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer1);
      Object object0 = new Object();
      List<Object> list1 = List.of((Object) integer1, (Object) list0, (Object) integer0, object0, object0);
      List<Object> list2 = Common.common(list0, list1);
      assertEquals(2, list2.size());
      assertTrue(list2.contains(0));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Integer integer0 = new Integer(0);
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer0);
      Object object0 = new Object();
      List<Object> list1 = List.of((Object) integer0, (Object) list0, (Object) integer0, object0, object0);
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      List<Object> list2 = Common.common(linkedList0, list1);
      assertFalse(list2.contains(0));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Integer integer0 = new Integer(0);
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer0);
      Object object0 = new Object();
      List<Object> list1 = List.of((Object) integer0, (Object) list0, (Object) integer0, object0, object0);
      List<Object> list2 = Common.common(list0, list1);
      assertTrue(list2.contains(0));
      assertEquals(1, list2.size());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Common common0 = new Common();
  }
}
