/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:48:54 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.DoubleTheDifference;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class DoubleTheDifference_ESTest extends DoubleTheDifference_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      Object object0 = new Object();
      Integer integer1 = new Integer(3017169);
      List<Object> list0 = List.of((Object) integer0, object0, object0, (Object) integer1, (Object) integer0, (Object) integer0, object0, (Object) "+\"OBLctm7G0q]FIGl8{");
      int int0 = DoubleTheDifference.doubleTheDifference(list0);
      assertEquals((-2021892959), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Object object0 = new Object();
      linkedList0.add(object0);
      List<Object> list0 = linkedList0.subList(0, 0);
      linkedList0.pollFirst();
      // Undeclared exception!
      try { 
        DoubleTheDifference.doubleTheDifference(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractList$SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        DoubleTheDifference.doubleTheDifference((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.DoubleTheDifference", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer(6);
      Integer integer1 = Integer.valueOf(1249);
      Object object0 = new Object();
      List<Object> list0 = List.of((Object) integer1, (Object) integer1, (Object) integer1, (Object) linkedList0, object0, (Object) integer0, (Object) linkedList0, (Object) integer1, object0, (Object) integer1);
      int int0 = DoubleTheDifference.doubleTheDifference(list0);
      assertEquals(7800005, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer(6);
      Object object0 = new Object();
      List<Object> list0 = List.of((Object) integer0, (Object) integer0, (Object) integer0, (Object) linkedList0, object0, (Object) integer0, (Object) linkedList0, (Object) integer0, object0, (Object) integer0);
      int int0 = DoubleTheDifference.doubleTheDifference(list0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DoubleTheDifference doubleTheDifference0 = new DoubleTheDifference();
  }
}
