/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:27:43 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.EvenOddPalindrome;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class EvenOddPalindrome_ESTest extends EvenOddPalindrome_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EvenOddPalindrome.evenOddPalindrome(1458);
      // Undeclared exception!
      EvenOddPalindrome.evenOddPalindrome(1938);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EvenOddPalindrome evenOddPalindrome0 = new EvenOddPalindrome();
  }
}
