/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:47:19 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Factorize;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Factorize_ESTest extends Factorize_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      List<Integer> list0 = Factorize.factorize(2370);
      assertFalse(list0.contains(2370));
      assertEquals(4, list0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Factorize.factorize(5641);
      // Undeclared exception!
      Factorize.factorize(5641);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      List<Integer> list0 = Factorize.factorize((-2012));
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Factorize factorize0 = new Factorize();
  }
}
