/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:07:28 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.FindMax;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class FindMax_ESTest extends FindMax_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      List<String> list0 = List.of("original.FindMax", "", "y'Z>jgjDf_E\u0000", "0YsCE0a*%G_D: +%", "_", "2d:o% d", "G^XI[SKLx23Hu+)>", "k.$bH XNC\"eC{zeo&", "G^XI[SKLx23Hu+)>");
      String string0 = FindMax.findMax(list0);
      assertEquals("G^XI[SKLx23Hu+)>", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("");
      List<String> list0 = linkedList0.subList(1, 1);
      linkedList0.add("");
      // Undeclared exception!
      try { 
        FindMax.findMax(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractList$SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.addLast((String) null);
      // Undeclared exception!
      try { 
        FindMax.findMax(linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.FindMax", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      List<String> list0 = List.of("k[dW", "*3iw", "", "|`jS)$qLrUk#!pK_7");
      String string0 = FindMax.findMax(list0);
      assertNotNull(string0);
      assertEquals("|`jS)$qLrUk#!pK_7", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("");
      String string0 = FindMax.findMax(linkedList0);
      assertTrue(linkedList0.contains(string0));
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      String string0 = FindMax.findMax(linkedList0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String string0 = FindMax.findMax((List<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      FindMax findMax0 = new FindMax();
  }
}
