/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:30:22 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.FizzBuzz;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class FizzBuzz_ESTest extends FizzBuzz_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FizzBuzz.fizzBuzz(5046);
      // Undeclared exception!
      FizzBuzz.fizzBuzz(5046);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = FizzBuzz.fizzBuzz((-8414));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FizzBuzz fizzBuzz0 = new FizzBuzz();
  }
}
