/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:45:38 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.GetClosestVowel;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class GetClosestVowel_ESTest extends GetClosestVowel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = GetClosestVowel.getClosestVowel(",tyUU _7ZTMh");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        GetClosestVowel.getClosestVowel((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.GetClosestVowel", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = GetClosestVowel.getClosestVowel("5P6_j.{U%eaa`k<f,");
      assertEquals("U", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = GetClosestVowel.getClosestVowel("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      GetClosestVowel getClosestVowel0 = new GetClosestVowel();
  }
}
