/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:41:46 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.GetPositive;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class GetPositive_ESTest extends GetPositive_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      List<Object> list0 = List.of((Object) integer0);
      List<Object> list1 = GetPositive.getPositive(list0);
      assertFalse(list1.contains((-1)));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        GetPositive.getPositive((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.GetPositive", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Integer integer0 = new Integer(460);
      List<Object> list0 = List.of((Object) integer0, (Object) integer0);
      List<Object> list1 = GetPositive.getPositive(list0);
      assertTrue(list1.contains(460));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Object object0 = new Object();
      List<Object> list0 = List.of((Object) integer0, (Object) integer0, (Object) integer0, object0, object0, object0, object0);
      List<Object> list1 = GetPositive.getPositive(list0);
      assertTrue(list1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      GetPositive getPositive0 = new GetPositive();
      List<Object> list0 = List.of((Object) getPositive0);
      List<Object> list1 = GetPositive.getPositive(list0);
      assertEquals(0, list1.size());
  }
}
