/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:19:43 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.GetRow;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class GetRow_ESTest extends GetRow_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      linkedList0.add((Object) linkedList0);
      linkedList0.add((Object) linkedList0);
      List<Object> list0 = GetRow.getRow(linkedList0, (-939));
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      LinkedList<Object> linkedList1 = new LinkedList<Object>();
      linkedList1.add((Object) linkedList0);
      Object object0 = new Object();
      linkedList0.add(object0);
      List<Object> list0 = GetRow.getRow(linkedList1, 1);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        GetRow.getRow((List<Object>) null, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.GetRow", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GetRow getRow0 = new GetRow();
      List<Object> list0 = List.of((Object) getRow0);
      // Undeclared exception!
      try { 
        GetRow.getRow(list0, (-4047));
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class original.GetRow cannot be cast to class java.util.List (original.GetRow is in unnamed module of loader org.evosuite.instrumentation.InstrumentingClassLoader @adce918; java.util.List is in module java.base of loader 'bootstrap')
         //
         verifyException("original.GetRow", e);
      }
  }
}
