/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:36:38 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Collection;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Intersection;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Intersection_ESTest extends Intersection_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer(566);
      Integer integer1 = new Integer((-1));
      Integer integer2 = new Integer(1);
      List<Integer> list0 = List.of(integer1, integer2, integer0, integer0);
      String string0 = Intersection.intersection(list0, list0);
      assertEquals("YES", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer integer0 = new Integer((-12));
      Integer integer1 = new Integer((-2044776971));
      List<Integer> list0 = List.of(integer1, integer0, integer0, integer1);
      // Undeclared exception!
      Intersection.intersection(list0, list0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Integer integer0 = new Integer(1);
      List<Integer> list0 = List.of(integer0, integer0, integer0);
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>(list0);
      List<Integer> list1 = linkedList0.subList(0, 1);
      linkedList0.addAll(0, (Collection<? extends Integer>) list1);
      // Undeclared exception!
      try { 
        Intersection.intersection(list1, list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractList$SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        Intersection.intersection((List<Integer>) null, (List<Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Intersection", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      // Undeclared exception!
      try { 
        Intersection.intersection(linkedList0, linkedList0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      List<Integer> list0 = List.of();
      // Undeclared exception!
      try { 
        Intersection.intersection(list0, list0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Integer integer0 = Integer.valueOf(0);
      Integer integer1 = new Integer(577);
      List<Integer> list0 = List.of(integer0, integer1, integer1, integer1);
      Integer integer2 = new Integer(552);
      List<Integer> list1 = List.of(integer2, integer1, integer0, integer2, integer1, integer2);
      String string0 = Intersection.intersection(list0, list1);
      assertEquals("NO", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Integer integer0 = Integer.valueOf((-12));
      Integer integer1 = new Integer(558);
      List<Integer> list0 = List.of(integer1, integer0, integer1, integer1);
      String string0 = Intersection.intersection(list0, list0);
      assertEquals("NO", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Integer integer0 = Integer.valueOf((-12));
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer0);
      String string0 = Intersection.intersection(list0, list0);
      assertEquals("NO", string0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Intersection intersection0 = new Intersection();
  }
}
