/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:35:21 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Pluck;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Pluck_ESTest extends Pluck_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer((-567));
      linkedList0.add((Object) integer0);
      List<Object> list0 = Pluck.pluck(linkedList0);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        Pluck.pluck((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Pluck", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Pluck pluck0 = new Pluck();
      Object object0 = new Object();
      Integer integer0 = Integer.getInteger((String) null, 2);
      List<Object> list0 = List.of(object0, object0, (Object) pluck0, object0, object0, object0, (Object) integer0, object0, object0, (Object) integer0);
      List<Object> list1 = Pluck.pluck(list0);
      List<Object> list2 = Pluck.pluck(list1);
      List<Object> list3 = Pluck.pluck(list2);
      List<Object> list4 = Pluck.pluck(list3);
      assertFalse(list4.equals((Object)list3));
      assertEquals(2, list3.size());
      assertTrue(list2.contains(2));
      assertTrue(list1.contains(2));
  }
}
