/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:12:21 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Collection;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.RescaleToUnit;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class RescaleToUnit_ESTest extends RescaleToUnit_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Double double0 = Double.valueOf(0.0);
      Double double1 = new Double((-5640.2675744));
      List<Double> list0 = List.of(double0, double0, double0, double0, double0, double1, double0);
      List<Double> list1 = RescaleToUnit.rescaleToUnit(list0);
      assertFalse(list1.contains((-5640.2675744)));
      assertEquals(7, list1.size());
      assertTrue(list1.contains(0.0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      List<Double> list0 = RescaleToUnit.rescaleToUnit(linkedList0);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      Double double0 = new Double((-428.49));
      linkedList0.add(double0);
      List<Double> list0 = linkedList0.subList(0, 0);
      linkedList0.addAll((Collection<? extends Double>) linkedList0);
      // Undeclared exception!
      try { 
        RescaleToUnit.rescaleToUnit(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractList$SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      linkedList0.add((Double) null);
      // Undeclared exception!
      try { 
        RescaleToUnit.rescaleToUnit(linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.RescaleToUnit", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Double double0 = new Double(1351.4672565847118);
      List<Double> list0 = List.of(double0, double0, double0, double0, double0, double0);
      List<Double> list1 = RescaleToUnit.rescaleToUnit(list0);
      assertFalse(list1.contains(1351.4672565847118));
      assertEquals(6, list1.size());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      RescaleToUnit rescaleToUnit0 = new RescaleToUnit();
  }
}
