/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 22:01:59 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.RoundedAvg;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class RoundedAvg_ESTest extends RoundedAvg_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RoundedAvg.roundedAvg((-3855), 2335);
      // Undeclared exception!
      RoundedAvg.roundedAvg((-3855), 2335);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Object object0 = RoundedAvg.roundedAvg(1, 0);
      assertEquals((-1), object0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Object object0 = RoundedAvg.roundedAvg((-1), (-1));
      assertEquals("0b11111111111111111111111111111111", object0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RoundedAvg roundedAvg0 = new RoundedAvg();
  }
}
