/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:01:18 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Skjkasdkd;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Skjkasdkd_ESTest extends Skjkasdkd_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer(25);
      Integer integer1 = new Integer(31);
      Integer integer2 = new Integer(3);
      List<Integer> list0 = List.of(integer0, integer0, integer1, integer0, integer2, integer2);
      int int0 = Skjkasdkd.skjkasdkd(list0);
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Integer integer0 = new Integer(1847);
      List<Integer> list0 = linkedList0.subList(0, 0);
      linkedList0.add(integer0);
      // Undeclared exception!
      try { 
        Skjkasdkd.skjkasdkd(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractList$SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        Skjkasdkd.skjkasdkd((List<Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Skjkasdkd", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Integer integer0 = new Integer(25);
      Integer integer1 = new Integer(0);
      List<Integer> list0 = List.of(integer0, integer0, integer1, integer0, integer1, integer1);
      int int0 = Skjkasdkd.skjkasdkd(list0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Integer integer0 = new Integer(25);
      Integer integer1 = new Integer(31);
      List<Integer> list0 = List.of(integer0, integer0, integer1, integer1, integer0, integer0);
      int int0 = Skjkasdkd.skjkasdkd(list0);
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Skjkasdkd skjkasdkd0 = new Skjkasdkd();
  }
}
