/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:14:27 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Collection;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.SortArray;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class SortArray_ESTest extends SortArray_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer(4);
      Integer integer1 = new Integer(1);
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer1, integer0);
      List<Object> list1 = List.copyOf((Collection<?>) list0);
      List<Object> list2 = SortArray.sortArray(list1);
      assertFalse(list2.equals((Object)list1));
      assertTrue(list2.contains(4));
      assertEquals(10, list2.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        SortArray.sortArray((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.SortArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Integer integer0 = new Integer(3866);
      Integer integer1 = new Integer(835);
      List<Object> list0 = List.of((Object) integer0, (Object) integer1, (Object) integer0);
      List<Object> list1 = SortArray.sortArray(list0);
      assertEquals(3, list1.size());
      assertTrue(list1.contains(3866));
      assertFalse(list1.equals((Object)list0));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Integer integer0 = new Integer((-1795));
      List<Object> list0 = List.of((Object) integer0, (Object) integer0);
      List<Object> list1 = SortArray.sortArray(list0);
      assertTrue(list1.equals((Object)list0));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      List<Object> list0 = SortArray.sortArray(linkedList0);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SortArray sortArray0 = new SortArray();
      List<Object> list0 = List.of((Object) sortArray0);
      // Undeclared exception!
      try { 
        SortArray.sortArray(list0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class original.SortArray cannot be cast to class java.lang.Number (original.SortArray is in unnamed module of loader org.evosuite.instrumentation.InstrumentingClassLoader @4def8e3a; java.lang.Number is in module java.base of loader 'bootstrap')
         //
         verifyException("original.SortArray", e);
      }
  }
}
