/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:49:59 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.StrangeSortList;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class StrangeSortList_ESTest extends StrangeSortList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        StrangeSortList.strangeSortList((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.StrangeSortList", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer integer0 = Integer.getInteger("|@1WTXof`W)<", 1978);
      Object object0 = new Object();
      List<Object> list0 = List.of((Object) integer0, (Object) integer0, object0, (Object) integer0, object0);
      List<Object> list1 = StrangeSortList.strangeSortList(list0);
      assertEquals(3, list1.size());
      assertFalse(list1.contains(object0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StrangeSortList strangeSortList0 = new StrangeSortList();
      List<Object> list0 = List.of((Object) strangeSortList0, (Object) strangeSortList0);
      List<Object> list1 = StrangeSortList.strangeSortList(list0);
      assertTrue(list1.isEmpty());
  }
}
