/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 22:21:58 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.SumToN;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class SumToN_ESTest extends SumToN_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = SumToN.sumToN(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SumToN.sumToN(3063);
      SumToN.sumToN(3063);
      SumToN.sumToN(3063);
      // Undeclared exception!
      SumToN.sumToN(2822);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SumToN sumToN0 = new SumToN();
  }
}
