/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:37:53 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.StartsOneEnds;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class StartsOneEnds_ESTest extends StartsOneEnds_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StartsOneEnds.startsOneEnds(11);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      StartsOneEnds.startsOneEnds(10);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = StartsOneEnds.startsOneEnds(4);
      assertEquals(1800, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = StartsOneEnds.startsOneEnds((-1));
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      StartsOneEnds startsOneEnds0 = new StartsOneEnds();
  }
}
