/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:31:31 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Collection;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.SumSquares1;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SumSquares1_ESTest extends SumSquares1_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer(20);
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer0, integer0);
      LinkedList<Object> linkedList0 = new LinkedList<Object>(list0);
      linkedList0.addAll((Collection<?>) list0);
      int int0 = SumSquares1.sumSquares(linkedList0);
      assertEquals(10, linkedList0.size());
      assertEquals(17680, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      int int0 = SumSquares1.sumSquares(linkedList0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer((-2396));
      Integer integer1 = new Integer(1);
      linkedList0.add((Object) integer1);
      linkedList0.add((Object) integer0);
      int int0 = SumSquares1.sumSquares(linkedList0);
      assertEquals(2, linkedList0.size());
      assertEquals((-2395), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        SumSquares1.sumSquares((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.SumSquares1", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Object object0 = new Object();
      linkedList0.add(object0);
      // Undeclared exception!
      try { 
        SumSquares1.sumSquares(linkedList0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class java.lang.Object cannot be cast to class java.lang.Integer (java.lang.Object and java.lang.Integer are in module java.base of loader 'bootstrap')
         //
         verifyException("original.SumSquares1", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SumSquares1 sumSquares1_0 = new SumSquares1();
  }
}
