/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:51:00 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.CountUpTo;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class CountUpTo_ESTest extends CountUpTo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      List<Object> list0 = CountUpTo.countUpTo((-1647));
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      CountUpTo.countUpTo(1392);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      List<Object> list0 = CountUpTo.countUpTo(150);
      assertFalse(list0.contains(150));
      assertEquals(35, list0.size());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CountUpTo countUpTo0 = new CountUpTo();
  }
}
