/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 19:56:34 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.CountNums;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class CountNums_ESTest extends CountNums_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = Integer.valueOf(0);
      linkedList0.add(0, (Object) integer0);
      linkedList0.add((Object) integer0);
      int int0 = CountNums.countNums(linkedList0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        CountNums.countNums((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.CountNums", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer(798);
      linkedList0.add((Object) integer0);
      int int0 = CountNums.countNums(linkedList0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Integer integer0 = Integer.valueOf((-2010));
      List<Object> list0 = List.of((Object) integer0);
      int int0 = CountNums.countNums(list0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CountNums countNums0 = new CountNums();
      List<Object> list0 = List.of((Object) countNums0, (Object) countNums0);
      // Undeclared exception!
      try { 
        CountNums.countNums(list0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class original.CountNums cannot be cast to class java.lang.Integer (original.CountNums is in unnamed module of loader org.evosuite.instrumentation.InstrumentingClassLoader @41112d01; java.lang.Integer is in module java.base of loader 'bootstrap')
         //
         verifyException("original.CountNums", e);
      }
  }
}
