/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:28:56 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Exchange;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Exchange_ESTest extends Exchange_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Integer integer0 = new Integer(0);
      List<Integer> list0 = List.of(integer0, integer0);
      linkedList0.add(integer0);
      String string0 = Exchange.exchange(linkedList0, list0);
      assertEquals("YES", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer integer0 = new Integer(7);
      List<Integer> list0 = List.of(integer0);
      String string0 = Exchange.exchange(list0, list0);
      assertEquals("NO", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Integer integer1 = new Integer((-2127));
      List<Integer> list0 = List.of(integer0, integer1);
      String string0 = Exchange.exchange(list0, list0);
      assertEquals("YES", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Integer integer0 = linkedList0.pollLast();
      linkedList0.add(integer0);
      // Undeclared exception!
      try { 
        Exchange.exchange(linkedList0, linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Exchange", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Exchange exchange0 = new Exchange();
  }
}
