/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 21:49:43 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.LargestPrimeFactor;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class LargestPrimeFactor_ESTest extends LargestPrimeFactor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = LargestPrimeFactor.largestPrimeFactor(3216);
      assertEquals(67, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LargestPrimeFactor.largestPrimeFactor(6553);
      // Undeclared exception!
      LargestPrimeFactor.largestPrimeFactor(6553);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = LargestPrimeFactor.largestPrimeFactor((-2710));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LargestPrimeFactor largestPrimeFactor0 = new LargestPrimeFactor();
  }
}
