/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 19:48:31 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Minpath;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Minpath_ESTest extends Minpath_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<List<Integer>> linkedList0 = new LinkedList<List<Integer>>();
      List<Integer> list0 = Minpath.minpath(linkedList0, (-1));
      assertFalse(linkedList0.contains(list0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<List<Integer>> linkedList0 = new LinkedList<List<Integer>>();
      Minpath.minpath(linkedList0, 5049);
      // Undeclared exception!
      Minpath.minpath(linkedList0, 5003);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<List<Integer>> linkedList0 = new LinkedList<List<Integer>>();
      List<Integer> list0 = Minpath.minpath(linkedList0, 675);
      List<List<Integer>> list1 = List.of(list0);
      // Undeclared exception!
      try { 
        Minpath.minpath(list1, 675);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.ArrayList$Itr", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        Minpath.minpath((List<List<Integer>>) null, (-1));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Minpath", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Integer integer0 = new Integer(0);
      List<Integer> list0 = List.of(integer0, integer0);
      List<List<Integer>> list1 = List.of(list0, list0, list0, list0, list0);
      // Undeclared exception!
      try { 
        Minpath.minpath(list1, 0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 2 Size: 2
         //
         verifyException("java.util.ImmutableCollections$AbstractImmutableList", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LinkedList<List<Integer>> linkedList0 = new LinkedList<List<Integer>>();
      List<Integer> list0 = List.of();
      linkedList0.add(list0);
      // Undeclared exception!
      try { 
        Minpath.minpath(linkedList0, 708);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LinkedList<List<Integer>> linkedList0 = new LinkedList<List<Integer>>();
      Integer integer0 = new Integer(1);
      Integer integer1 = new Integer((-1));
      List<Integer> list0 = List.of(integer0, integer1);
      linkedList0.offerFirst(list0);
      linkedList0.add(list0);
      List<Integer> list1 = Minpath.minpath(linkedList0, 975);
      assertEquals(2, linkedList0.size());
      assertTrue(list1.contains((-1)));
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      LinkedList<List<Integer>> linkedList0 = new LinkedList<List<Integer>>();
      List<Integer> list0 = Minpath.minpath(linkedList0, 675);
      List<List<Integer>> list1 = List.of(list0, list0, list0, list0, list0);
      List<Integer> list2 = Minpath.minpath(list1, 675);
      assertTrue(list1.contains(list2));
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Minpath minpath0 = new Minpath();
  }
}
