/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 20:35:19 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Pluck;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Pluck_ESTest extends Pluck_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Pluck pluck0 = new Pluck();
      Object object0 = new Object();
      Integer integer0 = new Integer(0);
      List<Object> list0 = List.of((Object) pluck0, (Object) pluck0, (Object) pluck0, (Object) pluck0, object0, object0, (Object) integer0, (Object) integer0, (Object) integer0);
      List<Object> list1 = Pluck.pluck(list0);
      List<Object> list2 = Pluck.pluck(list1);
      assertFalse(list2.equals((Object)list1));
      assertFalse(list2.contains(object0));
      assertTrue(list1.contains(0));
      assertTrue(list2.contains(0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      List<Object> list0 = linkedList0.subList(0, 0);
      Integer integer0 = new Integer(0);
      linkedList0.add((Object) integer0);
      // Undeclared exception!
      try { 
        Pluck.pluck(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractList$SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        Pluck.pluck((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Pluck", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Pluck pluck0 = new Pluck();
      Object object0 = new Object();
      Integer integer0 = new Integer(0);
      Integer integer1 = new Integer((-1));
      List<Object> list0 = List.of((Object) pluck0, (Object) pluck0, (Object) pluck0, (Object) pluck0, object0, object0, (Object) integer0, (Object) integer1, (Object) integer0);
      List<Object> list1 = Pluck.pluck(list0);
      assertTrue(list1.contains(0));
      assertFalse(list1.contains((-1)));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      List<Object> list0 = Pluck.pluck(linkedList0);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Pluck pluck0 = new Pluck();
      Integer integer0 = new Integer(0);
      List<Object> list0 = List.of((Object) pluck0, (Object) integer0, (Object) integer0, (Object) integer0);
      List<Object> list1 = Pluck.pluck(list0);
      List<Object> list2 = Pluck.pluck(list1);
      assertFalse(list2.equals((Object)list1));
      assertTrue(list1.contains(0));
      assertEquals(2, list2.size());
      assertTrue(list2.contains(0));
  }
}
