/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 19:44:49 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.RemoveVowels;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class RemoveVowels_ESTest extends RemoveVowels_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = RemoveVowels.removeVowels("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        RemoveVowels.removeVowels((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.RemoveVowels", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = RemoveVowels.removeVowels("!2i~?8TLf=tO/m*:D");
      assertEquals("!2~?8TLf=t/m*:D", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = RemoveVowels.removeVowels("2bTN5:Ie");
      assertEquals("2bTN5:", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String string0 = RemoveVowels.removeVowels(";'-Qh!~l'A}eL;E");
      assertEquals(";'-Qh!~l'}L;", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String string0 = RemoveVowels.removeVowels("|o);b_%]=");
      assertEquals("|);b_%]=", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String string0 = RemoveVowels.removeVowels("~NSL>Sc&:|yci2GaSd");
      assertEquals("~NSL>Sc&:|yc2GSd", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String string0 = RemoveVowels.removeVowels("C8UKeBA6XKsTaGv%a'1");
      assertEquals("C8KB6XKsTGv%'1", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      String string0 = RemoveVowels.removeVowels("0F0>u|e");
      assertEquals("0F0>|", string0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      RemoveVowels removeVowels0 = new RemoveVowels();
  }
}
