/*
 * This file was automatically generated by EvoSuite
 * Wed May 14 19:30:46 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Encode;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Encode_ESTest extends Encode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = Encode.encode("Zp479 /m");
      assertEquals("zP479 /M", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = Encode.encode("znUDX^0D2y1W99^dLkk");
      assertEquals("ZNwdx^0d2Y1w99^DlKK", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = Encode.encode("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        Encode.encode((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Encode", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String string0 = Encode.encode(":6j))Iqv+=G~e");
      assertEquals(":6J))kQV+=g~G", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String string0 = Encode.encode("original.Encode");
      assertEquals("QRKGKNCL.gNCQDG", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String string0 = Encode.encode("q]C0cA/4xy+uB");
      assertEquals("Q]c0Cc/4XY+Wb", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String string0 = Encode.encode("$.t%ji:@fOSUH]");
      assertEquals("$.T%JK:@Fqswh]", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Encode encode0 = new Encode();
  }
}
